/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;

import demo.service.dao.EmployeeDao;
import demo.service.repository.EmployeeRepository;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@SpringBootApplication
@ComponentScan("{demo.service}")
@EntityScan(basePackages = { "demo.service" })
@EnableSwagger2
public class DemoProjectApplication {

	@Value("$app.url")
	private static String appURL;
	
	
	public static void main(String[] args) {
		SpringApplication.run(DemoProjectApplication.class, args);
	}

	@Bean
	public Docket cartApi()
	{
		return new Docket(DocumentationType.SWAGGER_2).host(appURL)
				.select().apis(RequestHandlerSelectors.basePackage("demo.service.controller")).paths(PathSelectors.any()).build();
		
	}
	
	protected void addResourceHandlers(ResourceHandlerRegistry registry)
	{
		registry.addResourceHandler("swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/");
		registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
	}
	
	@Bean
    public CommandLineRunner bookDemo(EmployeeRepository empRepo) {
        return (args) -> {

            empRepo.save(new EmployeeDao("E1", "Designation1", 15000));
            empRepo.save(new EmployeeDao("E2", "Designation2", 16000));
            empRepo.save(new EmployeeDao("E3", "Designation3", 17000));
            empRepo.save(new EmployeeDao("E4", "Designation4", 18000));
        

        };
        
	
	}
}
