/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.service;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	DemoProjectApplication classUnderTest = new DemoProjectApplication();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
