/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.demo.app;

import org.junit.Test;

import com.demo.app.DemoProjectApplication;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	DemoProjectApplication classUnderTest = new DemoProjectApplication();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
